# SPDX-License-Identifier: Apache-2.0
# Autor/desenvolvedor: Elizandro Pacheco — NextHop Solutions® (https://nexthop.solutions/).
# Licença e atribuições: consulte LICENSE e NOTICE na raiz do repositório.
# Modificado em 2026-10-01: atualização da stack, testes, documentação e avisos.

filebeat.modules:
  - module: netflow
    log:
      enabled: true
      var.netflow_host: 0.0.0.0
      var.netflow_port: 2055
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: "${ELASTIC_PASSWORD}"
setup.kibana.host: "http://kibana:5601"
