filebeat.modules:
  - module: netflow
    log:
      enabled: true
      var.netflow_host: 0.0.0.0
      var.netflow_port: 2055
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: "${ELASTIC_PASSWORD}"
setup.kibana.host: "http://kibana:5601"
