apiVersion: 1
datasources:
  - name: Elasticsearch NetFlow
    uid: aeznn8invxnggb
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: true
    basicAuthUser: elastic
    isDefault: true
    jsonData:
      index: filebeat-*
      timeField: '@timestamp'
    secureJsonData:
      basicAuthPassword: $ELASTIC_PASSWORD
